version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: pg
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: lol
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: